"""
app/ingestion/contracts/contract_generator.py
=============================================
Production-grade dataset contract generator for enterprise pipelines.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional

import polars as pl
from loguru import logger


class ContractGenerator:
    """
    Enterprise dataset contract generator.
    Creates structured JSON configurations (contracts) defining dataset semantics,
    schemas, quality baselines, and access paths.
    """

    def __init__(self, output_base_dir: str = "/data/contracts"):
        """
        Initialize the ContractGenerator.

        Args:
            output_base_dir (str): Base root directory to output the JSON contracts.
        """
        self.output_base_dir = Path(output_base_dir)

    def generate(
        self,
        dataset_name: str,
        schema: Dict[str, pl.DataType],
        profiling_metadata: Dict[str, Any],
        version: str = "1.0.0",
        incremental_strategy: str = "append",
        watermark_column: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate a data contract from schema and profiling metadata.

        Args:
            dataset_name: Name of the dataset.
            schema: The schema dictionary from a Polars DataFrame (e.g. df.schema).
            profiling_metadata: JSON mapping of statistics generated by the DatasetProfiler.
            version: Schema versioning tracker.
            incremental_strategy: The ingestion strategy (e.g., append, upsert, overwrite).
            watermark_column: Column used to track incremental loads (if any).

        Returns:
            Dict[str, Any]: The assembled JSON contract.
        """
        logger.info(f"Generating contract for dataset '{dataset_name}' (Version: {version})")

        columns_profile = profiling_metadata.get("columns", {})

        # Assemble detailed schema field definitions
        schema_definitions = []
        quality_baselines = {}

        for col_name, dtype in schema.items():
            col_info = columns_profile.get(col_name, {})
            null_pct = col_info.get("null_percentage", 0.0)
            
            # Infer nullable attribute based on previous profiling
            # In an enterprise strict environment, if null% is 0, we can define nullable=False as a baseline
            is_nullable = True if null_pct > 0 else False

            schema_definitions.append({
                "name": col_name,
                "logical_type": str(dtype),
                "nullable": is_nullable
            })

            # Map baselines to monitor for future drift
            quality_baselines[col_name] = {
                "max_null_percentage_allowed": max(null_pct, 5.0), # Give a 5% flexibility or current
                "expected_type": str(dtype)
            }
            if "min" in col_info and col_info["min"] is not None:
                quality_baselines[col_name]["observed_min"] = col_info["min"]
            if "max" in col_info and col_info["max"] is not None:
                quality_baselines[col_name]["observed_max"] = col_info["max"]

        contract = {
            "dataset_name": dataset_name,
            "version": version,
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "schema": {
                "fields": schema_definitions
            },
            "quality_baselines": quality_baselines,
            "incremental_configuration": {
                "strategy": incremental_strategy,
                "watermark_column": watermark_column
            },
            "access_paths": {
                "parquet": f"/data/lake/{dataset_name}/"
            }
        }

        logger.debug(f"Contract generation successful for {dataset_name}. Contains {len(schema_definitions)} fields.")
        return contract

    def save_contract(self, dataset_name: str, contract: Dict[str, Any], version: str = "1.0.0") -> Path:
        """
        Save the structured JSON contract to the designated file system path.

        Args:
            dataset_name: Dataset identifier.
            contract: The generated config dictionary.
            version: Target version for filename formatting.

        Returns:
            Path: The full filepath where the contract was saved.
        """
        target_dir = self.output_base_dir / dataset_name
        target_dir.mkdir(parents=True, exist_ok=True)
        
        file_path = target_dir / f"contract_v{version}.json"
        
        try:
            with open(file_path, "w") as f:
                json.dump(contract, f, indent=2, default=str)
            logger.info(f"Dataset contract saved to: {file_path}")
            return file_path
        except Exception as e:
            logger.error(f"Failed to write dataset contract for '{dataset_name}': {e}")
            raise


# ==========================================
# Helper Utilities
# ==========================================

def run_contract_generator(
    dataset_name: str, 
    schema: Dict[str, pl.DataType], 
    profiling_metadata: Dict[str, Any],
    output_base_dir: str = "/data/contracts"
) -> Dict[str, Any]:
    """
    Utility wrapper to instantly generate and save a dataset contract.
    """
    generator = ContractGenerator(output_base_dir=output_base_dir)
    contract = generator.generate(dataset_name, schema, profiling_metadata)
    generator.save_contract(dataset_name, contract, version=contract["version"])
    return contract
